apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: codegen001
  janus-idp.io/tekton: codegen001
  backstage.io/kubernetes-id: codegen001
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: codegen001
resources:
  - application-dev.yaml
