apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-codegen001-gitops
spec:
  template:
    metadata:
      name: dsp-clone-job-codegen001-gitops
    spec:
      serviceAccountName: codegen001-dsp-job
      containers:
        - name: initialize-dsp
          image: quay.io/redhat-ai-dev/utils:latest
          command:
            - /bin/bash
            - -c
            - |
              NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
              oc wait -l statefulset=codegen001-notebook --for=condition=ready pod --timeout=300s
              oc exec  StatefulSet/codegen001-notebook -- git clone https://github.com/rhdh-pai-qe/codegen001
      restartPolicy: Never
