apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: codegen001
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codegen001
  name: codegen001
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
