apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: codegen001
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codegen001
  name: codegen001
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: codegen001
